name = "the-golden-hour-read"
type = "javascript"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "modules"
main = "./dist/server"

[env.production]
routes = [
  {
    pattern = "theunsaidbyrv.pages.dev/*",
    zone_name = "pages.dev"
  }
]

[observability]
enabled = true
